name: Deploy RNT Website
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore RNTWebsite/RNTWebsite.csproj

      - name: Build project
        run: dotnet build --configuration Release RNTWebsite/RNTWebsite.csproj

      - name: Run test
        run: dotnet test RNTWebsite/RNTWebsite.csproj

      - name: Run Website
        run: |
          dotnet run --project "RNTWebsite" &  # Executa o dotnet run em segundo plano
          PID=$!  # Pega o PID do processo em segundo plano
          sleep 60  # Aguarda 10 segundos para garantir que o servidor subiu

          # Verifica se o servidor está ouvindo nas portas corretas
          if ! ps aux | grep "dotnet" | grep -q "Now listening on"; then
              echo "Erro: O servidor não está ouvindo nas portas esperadas."
              exit 1
          fi