name: Deploy RNT Website
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    strategy:
      matrix:
        os: [macos-latest]
        runtime: [osx-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore RNTWebsite/RNTWebsite.csproj

      - name: Build project
        run: dotnet build --configuration Release RNTWebsite/RNTWebsite.csproj

      - name: Run the project in background
        run: dotnet run --project "RNTWebsite" &
        
      - name: Start ngrok tunnel
        run: ngrok http 5000 &

      - name: Wait for ngrok to start
        run: sleep 10  # Espera um pouco para o ngrok iniciar

      - name: Get ngrok URL
        run: |
          curl --silent --max-time 10 http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url

      - name: Finish deployment
        run: echo "Ngrok tunnel is active!"
     
      - name: Run test
        run: dotnet test RNTWebsite/RNTWebsite.csproj
