name: Deploy RNT Website
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.112

      - name: Restore dependencies
        run: dotnet restore RNTWebsite/RNTWebsite.csproj

      - name: Build project
        run: dotnet build --configuration Release RNTWebsite/RNTWebsite.csproj

  test:
    name: Test RNT Website
    runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.112
       
        - name: Run test
          run: dotnet test RNTWebsite/RNTWebsite.csproj
    